name: CI / MLOps Testing Pipeline
![CI](https://github.com/amasresha/generative-ai-testing/actions/workflows/ci.yml/badge.svg)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint code
        run: flake8 src tests

      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -q

  load-test:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Locust
        run: pip install locust

      - name: Run load test
        run: locust --headless -u 10 -r 2 -t 15s -f tests/test_load.py
